default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  url: <%= ENV["QR_ORDERING_DATABASE_URL"] %>

test:
  <<: *default
  url: <%= ENV["QR_ORDERING_TEST_DATABASE_URL"] || ENV["QR_ORDERING_DATABASE_URL"].sub("app_development", "app_test") %>

production:
  <<: *default
  url: <%= ENV["QR_ORDERING_DATABASE_URL"] %>
